name: aur-release-action
description: A composite action taking care of deploying software on the AUR
branding:
  icon: 'box'  
  color: 'green'

inputs:
  pkgbase:
    description: 'The name of the AUR project/repository'
    required: true
  private-key:
    description: 'The private key of the AUR user maintaining the project'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout with custom token
      uses: actions/checkout@v3.3.0
      if: inputs.token != ''
      with:
        reporitory: ssh://aur@aur.archlinux.org/${{ inputs.pkgbase }}.git
        fetch-depth: 0
        submodules: recursive
        ssh-key: ${{ inputs.private-key }}
        # Computed via ssh-keyscan aur.archlinux.org 
        ssh-known-hosts: |
          # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.0
          aur.archlinux.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLMiLrP8pVi5BFX2i3vepSUnpedeiewE5XptnUnau+ZoeUOPkpoCgZZuYfpaIQfhhJJI5qgnjJmr4hyJbe/zxow=
          # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.0
          aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN
          # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.0
          aur.archlinux.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKF9vAFWdgm9Bi8uc+tYRBmXASBb5cB5iZsB7LOWWFeBrLp3r14w0/9S2vozjgqY5sJLDPONWoTTaVTbhe3vwO8CBKZTEt1AcWxuXNlRnk9FliR1/eNB9uz/7y1R0+c1Md+P98AJJSJWKN12nqIDIhjl2S1vOUvm7FNY43fU2knIhEbHybhwWeg+0wxpKwcAd/JeL5i92Uv03MYftOToUijd1pqyVFdJvQFhqD4v3M157jxS5FTOBrccAEjT+zYmFyD8WvKUa9vUclRddNllmBJdy4NyLB8SvVZULUPrP3QOlmzemeKracTlVOUG1wsDbxknF1BwSCU7CmU6UFP90kpWIyz66bP0bl67QAvlIc52Yix7pKJPbw85+zykvnfl2mdROsaT8p8R9nwCdFsBc9IiD0NhPEHcyHRwB8fokXTajk2QnGhL+zP5KnkmXnyQYOCUYo3EKMXIlVOVbPDgRYYT/XqvBuzq5S9rrU70KoI/S5lDnFfx/+lPLdtcnnEPk=
          # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.0
          # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.0
        ssh-strict: true
    
    